// See https://aka.ms/new-console-template for more information
using Amazon_SDE_OA.Battle;
using Amazon_SDE_OA.Count_Binary_Substrings;
using Amazon_SDE_OA.Fill_the_Truck;
using Amazon_SDE_OA.Five_Star_Seller;
using Amazon_SDE_OA.Grid_Connections;
using Amazon_SDE_OA.Merge_Two_Sorted_Lists;
using Amazon_SDE_OA.Minimum_Difficulty_of_a_Job_Schedule;
using Amazon_SDE_OA.Music_Pairs;
using Amazon_SDE_OA.Number_Game;
using Amazon_SDE_OA.Reorder_Data_in_Log_Files;
using Amazon_SDE_OA.Robot_Bounded_in_Box;
using Amazon_SDE_OA.Shipment_Imbalance;
using Amazon_SDE_OA.Shopping_Options;
using Amazon_SDE_OA.Simple_Cipher;
using Amazon_SDE_OA.Slowest_key;
using Amazon_SDE_OA.Split_String_Into_Unique_Primes;
using Amazon_SDE_OA.Storage_Optimization;
using Amazon_SDE_OA.Top_K_Frequent_Words;
using Amazon_SDE_OA.Two_Sum_Unique_Pairs;

Console.WriteLine("Amazon SDE OA problems.");
Console.WriteLine("------------------------------\n");

//new Robot_Bounded_in_Box().Solution();
//Console.WriteLine();
//new Number_Game().Solution();
//Console.WriteLine();
//new Shopping_Options().Solution();
//Console.WriteLine();
//new Fill_the_Truck().Solution();
//Console.WriteLine();
//new Music_Pairs().Solution();
//Console.WriteLine();
//new Slowest_key().Solution();
//Console.WriteLine();
//new Five_Star_Seller().Solution();
//Console.WriteLine();
//new Split_String_Into_Unique_Primes().Solution();
//Console.WriteLine();
//new Storage_Optimization().Solution();
//Console.WriteLine();
//new Minimum_Difficulty_of_a_Job_Schedule().Solution();
//Console.WriteLine();
//new Merge_Two_Sorted_Lists().Solution();
//Console.WriteLine();
//new Two_Sum_Unique_Pairs().Solution();
//Console.WriteLine();
//new Reorder_Data_in_Log_Files().Solution();
//Console.WriteLine();
//new Top_K_Frequent_Words().Solution();
//Console.WriteLine();
//new Count_Binary_Substrings().Solution();
//Console.WriteLine();
//new Grid_Connections().Solution();
//Console.WriteLine();
//new Shipment_Imbalance().Solution();
//Console.WriteLine();
//new Simple_Cipher().Solution();
//Console.WriteLine();

//Battle part:
new Amazon_Battle1().Solution();